# Criando um programa teste apenas para armazenar no github

print('Hello World')
print('Teste de commit')
print('Teste de push')
print('Teste de pull')
print('Teste de clone')
print('Teste de branch')
print('Teste de merge')
print('Teste de rebase')
print('Teste de tag')
print('Teste de stash')
print('Teste de reset')
print('Teste de revert')
print('Teste de cherry-pick')
print('Teste de fetch')
print('Teste de checkout')
print('Teste de status')
print('Teste de log')
print('Teste de diff')
print('Teste de blame')
print('Teste de show')
